services:
  telegram-bot:
    build: .
    # container_name: nextmavens-telegram-bot
    env_file:
      - .env
    environment:
      - PORT=${PORT:-3002}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
    ports:
      - "3005:3002"
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
